import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from '@/app/(beforeLogin)/_component/main.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          {children}
          {modal}
        </div>
      </body>
    </html>
  );
}
